// Flujos del cliente sobre la misma API y PostgreSQL aislados del harness Admin.
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
module.exports = async function ({ chrome:c, origin, output, pool, request, admin, user, password,
  adminSupply, userSupply, png, wait, pause, ok, expiredToken }) {
  const receipt = await request('POST','/api/admin/recibos',admin.token,{numero_suministro:userSupply,
    periodo:'Cliente UI fixture',fecha_emision:'2026-10-01',fecha_vencimiento:'2030-11-01',monto:45,consumo_m3:15},201);
  const dates=(await pool.query('SELECT fecha_emision::text,fecha_vencimiento::text FROM recibos WHERE id_recibo=$1',[receipt.recibo.id_recibo])).rows[0];
  assert.equal(dates.fecha_emision,'2026-10-01');assert.equal(dates.fecha_vencimiento,'2030-11-01');
  await request('POST','/api/admin/cortes',admin.token,{alcance:'Zona',distrito:'Distrito fixture',zona:'Zona fixture',
    motivo:'Corte cliente fixture',fecha_inicio:'2030-01-01T09:00:00',fecha_fin:'2030-01-01T12:00:00'},201);
  await c.goto(origin+'/cliente/index.html');
  await require('./visual-checks.cjs').matrix(c,output,'client-login','client');
  await c.evaluate(`window.__sockets=[];const originalIO=window.io;window.io=Object.assign((...args)=>{const s=originalIO(...args);__sockets.push(s);return s;},originalIO);void 0;`);
  await c.evaluate('location.hash="admin-usuarios"'); await pause(150);
  assert.equal(await c.evaluate('document.querySelectorAll("[id*=admin]").length'),0);
  assert.equal(await c.evaluate('document.getElementById("view-dashboard").classList.contains("active")'),false);
  async function login(supply, pass=password) {
    await c.fill('#suministro',supply);await c.fill('#password',pass);await c.submit('#login-form');
  }
  const before=c.requests.length;
  await login(adminSupply);
  await wait(()=>c.evaluate('document.getElementById("form-error").textContent.includes("exclusiva para clientes")'),'rechazo admin en cliente');
  assert.equal(await c.evaluate('sessionStorage.getItem("hm_token")'),null);
  assert.equal(await c.evaluate('__sockets.length'),0);
  assert.equal(c.requests.slice(before).filter(r=>/\/api\/(me|admin)\//.test(r.url)).length,0);
  ok('Cliente: admin rechazado sin cargar datos; hash sin sesión bloqueado; ninguna pantalla administrativa');
  await login(userSupply);
  await wait(()=>c.evaluate('document.getElementById("view-dashboard").classList.contains("active")'),'dashboard cliente');
  await wait(()=>c.evaluate('document.getElementById("pay-list").textContent.includes("30.00")'),'pagos originales fixture');
  await wait(()=>c.evaluate('__sockets.filter(s=>s.connected).length===1'),'socket cliente');
  assert.equal(await c.evaluate('document.getElementById("toast").textContent'),'','login limpio sin avisos de otra sesión');
  await pause(1500);
  if(await c.evaluate('document.getElementById("spotlight-pop").classList.contains("open")'))await c.click('#spot-skip');
  await wait(()=>c.evaluate('!document.body.classList.contains("tutorial-open")'),'tutorial inicial cerrado');
  await require('./visual-checks.cjs')(c,output,'client-dashboard');
  await require('./visual-checks.cjs')(c,output,'client-dashboard-mobile',390,844);
  await require('./visual-checks.cjs')(c,output,'client-dashboard-landscape',640,360);
  await require('./visual-checks.cjs').matrix(c,output,'client-dashboard','client');
  assert.equal(await c.evaluate('document.getElementById("stat-debt").textContent'),'S/ 45.00');
  await c.evaluate('window.dispatchEvent(new Event("offline"))');
  assert.equal(await c.evaluate('document.getElementById("client-connection").dataset.state'),'offline');
  await c.evaluate('window.dispatchEvent(new Event("online"))');
  async function nav(name, expression) {
    await c.click('[data-sec="'+name+'"]');
    await wait(()=>c.evaluate('document.getElementById('+JSON.stringify('sec-'+name)+').classList.contains("active")'),'navegación cliente '+name);
    if(expression)await wait(()=>c.evaluate(expression),'cliente '+name);
    await require('./visual-checks.cjs')(c,output,'client-'+name);
    await require('./visual-checks.cjs').matrix(c,output,'client-'+name,'client');
  }
  await c.evaluate('location.hash="admin-recibos"');await pause(500);
  assert.equal(await c.evaluate('document.querySelector(".dash-sec.active").id'),'sec-inicio');
  await nav('historial','document.getElementById("cards").textContent.includes("Cliente UI fixture")');
  await require('./visual-checks.cjs')(c,output,'client-recibos-small',320,760);
  await c.evaluate(`(()=>{const card=[...document.querySelectorAll('#cards .card')].find(n=>n.textContent.includes('Cliente UI fixture'));card.querySelector('[data-act=detail]').click();})()`);
  await wait(()=>c.evaluate('document.getElementById("detail-modal").classList.contains("open")'),'detalle recibo');
  await require('./visual-checks.cjs').matrix(c,output,'client-recibo-modal','client');
  const downloads=path.resolve(__dirname,'../../artifacts/pdf/tests',path.basename(output));
  fs.mkdirSync(downloads,{recursive:true});
  fs.symlinkSync(path.relative(output,downloads),path.resolve(output,'pdf'),'dir');
  await c.command('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:downloads},false);
  await c.click('#btn-pdf');
  await wait(()=>fs.readdirSync(downloads).some(n=>n.endsWith('.pdf')),'recibo PDF');
  await c.click('#btn-pay-detail');
  await require('./visual-checks.cjs').matrix(c,output,'client-pago-modal','client');
  await c.evaluate('document.getElementById("pay-confirm").click();document.getElementById("pay-confirm").click();');
  await wait(async()=>Number((await pool.query('SELECT count(*) AS n FROM pagos WHERE id_recibo=$1',[receipt.recibo.id_recibo])).rows[0].n)===1,'pago persistido');
  await wait(()=>c.evaluate('!document.getElementById("pay-success").hidden'),'pago confirmado');
  await c.click('#pay-constancia');
  await wait(()=>fs.readdirSync(downloads).filter(n=>n.endsWith('.pdf')).length===2,'constancia PDF');
  for(const name of fs.readdirSync(downloads).filter(n=>n.endsWith('.pdf'))){
    const content=fs.readFileSync(path.join(downloads,name));assert.equal(content.subarray(0,5).toString(),'%PDF-');assert.ok(content.length>1000);assert.ok(content.length<40000,'PDF A4 con emblema por debajo de 40 KB');
  }
  await c.click('#pay-done');await pause(250);await c.click('#detail-close');
  await wait(()=>c.evaluate('document.getElementById("stat-debt").textContent==="S/ 0.00"'),'deuda actualizada tras pago');
  await nav('pagos','document.getElementById("pay-list").textContent.includes("45.00")');
  await nav('inicio','document.getElementById("sec-inicio").classList.contains("active")');
  await c.click('#btn-copies-head');await wait(()=>c.evaluate('document.querySelectorAll("#copies-tbody tr").length>0'),'copias recibos');await c.click('#copies-close');
  ok('Cliente: dashboard/consumos, recibos/detalle/copias, registro e historial de pago y dos PDF descargados');
  await nav('incidencias','document.getElementById("inc-list").textContent.includes("Reporte de prueba aislada")');
  await c.click('#btn-nueva-incidencia');
  await require('./visual-checks.cjs').matrix(c,output,'client-incidencia-form','client');
  await c.fill('#inc-tipo','Fuga de agua');await c.fill('#inc-desc','Incidencia cliente con foto y ubicación fixture');await c.fill('#inc-dir','Dirección cliente fixture');
  const photo=path.resolve(output,'fixture.png');fs.writeFileSync(photo,Buffer.from(png,'base64'));
  const {root}=await c.command('DOM.getDocument');const {nodeId}=await c.command('DOM.querySelector',{nodeId:root.nodeId,selector:'#inc-foto'});
  await c.command('DOM.setFileInputFiles',{nodeId,files:[photo]});
  await wait(()=>c.evaluate('!document.getElementById("inc-foto-prev").hidden'),'foto seleccionada');
  await c.command('Browser.grantPermissions',{origin,permissions:['geolocation']},false);
  await c.command('Emulation.setGeolocationOverride',{latitude:-12.05,longitude:-77.03,accuracy:10});
  await c.click('#inc-geo');await wait(()=>c.evaluate('document.getElementById("inc-coords").textContent.includes("-12.05")'),'geolocalización simulada');
  await c.submit('#inc-form');await wait(()=>c.evaluate('!document.getElementById("inc-ok").hidden'),'registro incidencia');
  const row=(await pool.query("SELECT foto_mime,latitud,longitud FROM incidencias WHERE descripcion='Incidencia cliente con foto y ubicación fixture'")).rows[0];
  assert.equal(row.foto_mime,'image/png');assert.equal(Number(row.latitud),-12.05);assert.equal(Number(row.longitud),-77.03);
  await c.click('#inc-view');await wait(()=>c.evaluate('document.getElementById("inc-list").textContent.includes("Incidencia cliente con foto")'),'incidencias actualizadas');
  await c.evaluate(`(()=>{const button=[...document.querySelectorAll('#inc-list button')].find(n=>/foto/i.test(n.textContent));if(!button)throw Error('Sin foto');button.click();})()`);
  await wait(()=>c.evaluate('document.getElementById("foto-img").naturalWidth>0'),'foto autenticada cliente');await c.click('#foto-close');
  await nav('cortes','document.getElementById("cortes-list").textContent.includes("Corte cliente fixture")');
  await nav('notificaciones','document.getElementById("notif-list").children.length>0');
  await c.evaluate(`(()=>{const b=[...document.querySelectorAll('#notif-list button')].find(n=>/leída/i.test(n.textContent));if(!b)throw Error('Sin notificación pendiente');b.click();})()`);
  await wait(async()=>Number((await pool.query('SELECT count(*) AS n FROM notificaciones_lecturas')).rows[0].n)>0,'notificación leída');
  await nav('ayuda','document.getElementById("ate-list").textContent.includes("Consulta fixture")');
  await c.fill('#ate-categoria','Facturación');await c.fill('#ate-asunto','Consulta cliente UI');await c.fill('#ate-desc','Solicitud creada desde la interfaz cliente aislada');await c.submit('#ate-form');
  await wait(()=>c.evaluate('document.getElementById("ate-list").textContent.includes("Consulta cliente UI")'),'atención cliente');
  await nav('perfil','document.getElementById("pf-correo").textContent==="cliente@fixture.invalid"');
  await c.click('#btn-change-pass');await c.fill('#pass-actual',password);await c.fill('#pass-nueva','ClienteNuevo123');await c.fill('#pass-confirm','ClienteNuevo123');await c.submit('#pass-form');
  await wait(()=>c.evaluate('!document.getElementById("pass-modal").classList.contains("open")'),'contraseña actualizada');
  await request('POST','/api/auth/login',null,{numero_suministro:userSupply,password:'ClienteNuevo123'},200);
  ok('Cliente: incidencias con foto y ubicación simulada, cortes, notificaciones/leída, atención, perfil y contraseña persistidos');
  await c.click('#hb-fab');await c.fill('#hb-input','Mis recibos');await c.submit('#hb-form');
  await wait(()=>c.evaluate('document.getElementById("hb-body").textContent.includes("Mis recibos")'),'HidroBot');
  await c.click('#btn-replay-tutorial');await wait(()=>c.evaluate('document.getElementById("spotlight-pop").classList.contains("open")'),'tutorial');
  if(process.env.HIDRO_TEST_FULL_TUTORIAL==='1'){
    const total=Number(await c.evaluate('document.getElementById("spot-total").textContent'));
    for(let step=1;step<=total;step++){
      await wait(()=>c.evaluate('document.getElementById("spot-num").textContent==='+JSON.stringify(String(step))),'paso tutorial '+step);
      await pause(350);await c.click('#spot-next');
    }
    await wait(()=>c.evaluate('!document.body.classList.contains("tutorial-open")'),'tutorial completado');
    ok('Cliente: tutorial completo, todos los pasos y regreso a navegación normal');
  }else await c.click('#spot-skip');
  await wait(()=>c.evaluate('!document.querySelector(".overlay.open,.overlay.closing")'),'modales cerrados antes del menú móvil');
  await c.command('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await c.click('#btn-menu');await wait(()=>c.evaluate('document.getElementById("shell").classList.contains("nav-open")'),'menú móvil');
  await c.evaluate('document.dispatchEvent(new KeyboardEvent("keydown",{key:"Escape",bubbles:true}))');
  await wait(()=>c.evaluate('!document.getElementById("shell").classList.contains("nav-open")'),'cerrar menú móvil');
  assert.equal(await c.evaluate('__sockets.length'),1);
  await c.screenshot(path.join(output,'client-mobile.png'));
  ok('Cliente: HidroBot, tutorial, navegación móvil en Chromium y un solo Socket.IO');
  await c.command('Emulation.clearDeviceMetricsOverride');
  await c.evaluate(`const originalFetch=window.fetch;window.fetch=async(...args)=>{const r=await originalFetch(...args);if(String(args[0]).includes('/api/me/perfil'))await new Promise(resolve=>setTimeout(resolve,900));return r;};`);
  await nav('perfil');await pause(100);await c.click('#btn-logout');await pause(1100);
  assert.equal(await c.evaluate('sessionStorage.getItem("hm_token")'),null);
  assert.equal(await c.evaluate('document.body.textContent.includes("cliente@fixture.invalid")'),false);
  assert.equal(await c.evaluate('document.querySelectorAll("img[src^=blob]").length'),0);
  assert.equal(await c.evaluate('document.querySelectorAll("#cards .card,#inc-list .inc-item,#pay-list .card,#ate-list .inc-item,#notif-list .inc-item").length'),0);
  assert.equal(await c.evaluate('document.querySelectorAll("#home-payment-list>*,#home-service-list>*,#home-notification-list>*").length'),0,'Actividad privada limpia tras logout');
  assert.equal(await c.evaluate('document.getElementById("suministro").value'), '');
  await wait(()=>c.evaluate('__sockets.filter(s=>s.connected).length===0'),'logout Socket');
  await c.evaluate('location.hash="perfil"');await pause(100);
  assert.equal(await c.evaluate('document.getElementById("view-dashboard").classList.contains("active")'),false);
  ok('Cliente: logout limpia datos/fotos/formularios/token/socket; respuesta tardía y hash no reabren la sesión');
  await c.click('#show-register');
  await require('./visual-checks.cjs').matrix(c,output,'client-register','client');
  for(const [id,value] of Object.entries({'reg-correo':'registro@fixture.invalid','reg-suministro':'900000003','reg-pass':password,'reg-pass2':password}))await c.fill('#'+id,value);
  await c.submit('#register-form');
  await wait(async()=>Number((await pool.query("SELECT count(*) AS n FROM usuarios WHERE correo='registro@fixture.invalid' AND rol='usuario'")).rows[0].n)===1,'registro cliente');
  await wait(()=>c.evaluate('document.getElementById("register-form").hidden'),'volver login');await login('900000003');
  await wait(()=>c.evaluate('document.getElementById("view-dashboard").classList.contains("active")'),'login nuevo usuario');
  await nav('perfil','document.getElementById("pf-correo").textContent==="registro@fixture.invalid"');
  assert.equal(await c.evaluate('document.body.textContent.includes("cliente@fixture.invalid")'),false);
  await wait(()=>c.evaluate('__sockets.filter(s=>s.connected).length===1'),'socket nuevo usuario');
  assert.equal(await c.evaluate('__sockets.length'),2);
  await c.evaluate(`const expiryFetch=window.fetch;window.fetch=(url,options={})=>expiryFetch(url,String(url).includes('/api/me/perfil')?{...options,headers:{...options.headers,Authorization:'Bearer '+${JSON.stringify(expiredToken)}}}:options);`);
  await c.click('[data-sec="inicio"]');await pause(200);await c.click('[data-sec="perfil"]');
  await wait(()=>c.evaluate('!document.getElementById("view-dashboard").classList.contains("active")'),'cierre por JWT expirado');
  assert.equal(await c.evaluate('sessionStorage.getItem("hm_token")'),null);
  assert.equal(await c.evaluate('document.body.textContent.includes("registro@fixture.invalid")'),false);
  await wait(()=>c.evaluate('__sockets.filter(s=>s.connected).length===0'),'Socket cerrado por expiración');
  ok('Cliente: JWT expirado cierra sesión, limpia datos y desconecta Socket.IO');
  assert.equal(c.requests.filter(r=>r.url.startsWith(origin+'/cliente/')&&/admin\.(js|css)/.test(r.url)).length,0);
  ok('Cliente: registro real, nuevo login sin datos heredados ni conexiones duplicadas');
};
